Neue Fotos eingefügt
ka-wagner/zwergenland pull request #8
Opened 2021-07-13 14:49 UTC by kaitimmer

Neue Bilder für den Rundgang und die Startseite

2021-07-15 06:58 UTC, maob84 requested changes
Hi Kai, ich weiß nicht ob es an mir liegt; auf jeden Fall ist die neue Seite (also mit den neuen Fotos) unendlich langsam bei mir (im Vergleich zur alten). Es dauert ungefähr 5 Sekund bis sich die Startseite aufgebaut hat. Der Rundgang ist dann gar nicht benutzbar. Hat das was mit dem Preview zu tun (wobei mir das bei der alten Seite bei Reviews nicht aufgefallen ist) oder sind die Bilder einfach deutlich größer (und mehr)?

2021-07-15 12:10 UTC, ofcourseican commented
> Hi Kai, ich weiß nicht ob es an mir liegt; auf jeden Fall ist die neue Seite (also mit den neuen Fotos) unendlich langsam bei mir (im Vergleich zur alten). Es dauert ungefähr 5 Sekund bis sich die Startseite aufgebaut hat. Der Rundgang ist dann gar nicht benutzbar. Hat das was mit dem Preview zu tun (wobei mir das bei der alten Seite bei Reviews nicht aufgefallen ist) oder sind die Bilder einfach deutlich größer (und mehr)?

Das stimmt. Ich vermute ich muss die Bilder mal in eine ordentliche Größe bringen. Mache ich dann noch.

2021-07-21 09:14 UTC, maob84 commented
Okay, Startseite lädt jetzt schnelle. Beim "Rundgang" dauert es beim ersten Mal, wenn es noch nicht im Cache ist, auch relativ lange. Damit kann man vielleicht leben. Ich gebe es frei.

2021-07-21 09:15 UTC, maob84 approved these changes

2021-07-23 17:10 UTC, merged